//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserText
    {
        public int UserTextId { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public System.DateTimeOffset Added { get; set; }
    }
}
